name: Deploy Lambda Layer
on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest  # Change to your preferred runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-preferred-aws-region  # Replace with your preferred region

      - name: Deploy Lambda Layer
        run: |
          # Here, you can use the AWS CLI or SDKs to deploy the Lambda layer
          # For example, using AWS CLI:
          aws lambda publish-layer-version \
            --layer-name YourLayerName \
            --description "Your layer description" \
            --license-info "Your license info" \
            --content S3Bucket=lambda-layer-bucket-name,S3Key=path-to-layer-zip-file.zip \
            --compatible-runtimes python3.8  # Replace with your layer's compatible runtimes

          # Optionally, you can update your Lambda functions to use the newly deployed layer

# Doc: https://github.com/marketplace/actions/configure-aws-credentials-for-github-actions